# Nome da aplicação (aparece nos logs e no Actuator)
spring.application.name=chronus
# Perfil ativo: lê da variável de ambiente SPRING_PROFILES_ACTIVE
# Se não definida, usa "dev" como padrão

# Porta em que o Chronus vai escutar localmente
server.port=8081
#spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# JPA — configurações comuns
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Upload de arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Agendamentos habilitados
spring.task.scheduling.enabled=true